export const urls = [
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ",
  "p7gFHxlSpx0",
  "OXgO7L1xZ7A",
  "aRg4TQzh4uQ"
]

const videos = [
  { url: "p7gFHxlSpx0", title: "Je viens de lire 'Éloge des frontières' de Régis Debray", date: "15/01/2024" }, 
  { url: "", title: "", elapsed: "" }, 
  { url: "", title: "", elapsed: "" }, 
  { url: "", title: "", elapsed: "" },   
]
